const translations = {
    zh: {
         // side
        "side-aboutme":"關於LAI的事情",
        "side-slime":"史萊運轉",
        "side-ice":"破冰溝溝GO",
        "side-eraser":"腦內橡皮擦",
        "side-toki":"偷去",
        "side-seeyou":"大新街 LAST DANCE",
        "side-web":"網頁作品",
        "side-graphic":"平面作品",
        //
        "load": "不安と彷徨いを乗り越えて、自分を探す糸",
        "cover01":"字體設計 / 手工作業",
        "cover02":"2023 / 珍珠板, 大頭釘, 紙",
        "poem01":"腦中有一塊橡皮擦，像鍵盤上的刪除鍵，正刪除過去的一點一滴",
        "poem02":"無數次的停滯，躺在零碎的拼圖裡，努力拼出，完整的自己",
        "element01":'腦中',
        "element01-1":"為了使立體化後的光影效果更明確、可視度更高，在字體設計時主要以不使用圓弧状的方形與直線結構。使用方格結構加工的文字呈現了微微的機械感。與詩中「自我混肴」的概念符合。",
        "element02":"鍵盤",
        "element02-1":"雖然想以機械感來呈現作品概念,但為了避免過度使用方形結構使整體看起來過於生硬乖僻，因此也加入了小方形與圓形作為裝飾。在這項文字作品裡，「X」形狀的交叉結構便以圓形製作。",
        "element03":"無數次",
        "element03-1":"在文字結構方面盡可能簡化了複雜的筆畫部分。具體來説是將筆畫密度較高的地方以筆畫重構等方式來使視覺呈現上更為簡潔。此外，也調整筆畫間距使文字全體重心一致。",
        "structure01":"文字的立體化",
        "structure02":"成品立體化的效果，主要是以文字的光影投射在背景的白色珍珠版的形式呈現。為了讓光影呈現出不同的變化，將文字的分成三種不同的高度，以摺紙片的方式來製作高度差。字體設計的工作完成之後，將設計的字型製作為實體厚紙片，在摺紙的同時一邊確認腦袋裡預設的立體模型沒有造成字型的嚴重走鐘。",
        "structure03":"最上層",
        "structure04":"中間層",
        "structure05":"最下層",
        "structure06":"實作物",
    },
    en: {
         // side
        "side-aboutme":"Things about LAI",
        "side-slime":"Tranditional Taiwanese snack renewal",
        "side-ice":"Onepage adult educational site",
        "side-eraser":"Typography & 3D-artwork",
        "side-toki":"The path I walked pass",
        "side-seeyou":"Project & visual design",
        "side-web":"When I meet programming",
        "side-graphic":"Some graphic works here",
        //
        "load": "Lines about anxiety and concern come to knock",
        "cover01":"Typography / Handcrafted",
        "cover02":"2023 / Foam Board, Push Pins, Paper",
        "poem01":"There's an eraser in my head, like the delete on a keyboard, which is erasing bit by bit.",
        "poem02":"Countless moments of stagnation, lying in scattered puzzle pieces, trying to piece together compelete self.",
        "element01":'腦中<span style="font-size: 16px;">/In my head</span>',
        "element01-1":"To create clearer light and shadow effects, the typeface uses rectangular forms and straight lines instead of curves. Its grid-based structure adds mechanical quality, reflecting the poem's theme of a confused sense of self.",
        "element02":'鍵盤<span style="font-size: 16px;">/Keyboard',
        "element02-1":"To soften the rigid mechanical aesthetic, small squares and circles were added as decorative elements. For example, circular forms are used in the structure of the “X.”",
        "element03":'無數次<span style="font-size: 16px;">/Countless',
        "element03-1":"Complex strokes were simplified and reconstructed to create cleaner letterforms. Stroke spacing was also adjusted to maintain consistent visual balance.",
        "structure01":"Three-Dimensional Typography",
        "structure02":"The typography is arranged at three different heights, casting varied shadows onto the white foam board behind it. Folded paper structures create the height differences while preserving the original letterforms.",
        "structure03":"Top Layer",
        "structure04":"Middle Layer",
        "structure05":"Bottom Layer",
        "structure06":"Physical Prototype",
    }
};