const translations = {
    zh: {
         // side
        "side-aboutme":"關於LAI的事情",
        "side-slime":"史萊運轉",
        "side-ice":"破冰溝溝GO",
        "side-eraser":"腦內橡皮擦",
        "side-toki":"偷去",
        "side-seeyou":"大新街 LAST DANCE",
        "side-web":"網頁作品",
        "side-graphic":"平面作品",
        //
        "load": "自由に、自分らしく、思い切り振る舞う糸",
        "cover-title":"平面作品",
        "cover01":"樹脂 / 立體作品",
        "works01-1":"",
        "works01-2":"",
        "works01-3":"",
        "works01-4":"",
        "works02-1":"",
        "works02-2":"",
        "works02-3":"",
        "works02-4":"",
        "works03-1":"",
        "works03-2":"",
        "works03-3":"",
        "works04-1":"",
        "works04-2":"",
        "works04-3":"",
        "works05-1":"",
        "works05-2":"",
        "works06-1":"",
        "works06-2":"",
        "works06-3":"",
        "works07-1":"",
        "works07-2":"",
        "works07-3":"",
        "works08-1":"",
        "works08-2":"",
        "works09-1":"",
        "works09-2":"",
    },
    en: {
         // side
        "side-aboutme":"Things about LAI",
        "side-slime":"Tranditional Taiwanese snack renewal",
        "side-ice":"Onepage adult educational site",
        "side-eraser":"Typography & 3D-artwork",
        "side-toki":"The path I walked pass",
        "side-seeyou":"Project & visual design",
        "side-web":"When I meet programming",
        "side-graphic":"Some graphic works here",
        //
        "load": "Lines about split liberally and work as my-style",
        "cover-title":"TOKI",
        "cover01":"Resin / 3D Artwork",
        "works01-1":"",
        "works01-2":"",
        "works01-3":"",
        "works01-4":"",
        "works02-1":"",
        "works02-2":"",
        "works02-3":"",
        "works02-4":"",
        "works03-1":"",
        "works03-2":"",
        "works03-3":"",
        "works04-1":"",
        "works04-2":"",
        "works04-3":"",
        "works05-1":"",
        "works05-2":"",
        "works06-1":"",
        "works06-2":"",
        "works06-3":"",
        "works07-1":"",
        "works07-2":"",
        "works07-3":"",
        "works08-1":"",
        "works08-2":"",
        "works09-1":"",
        "works09-2":"",
    }
};