const translations = {
    zh: {
         // side
        "side-aboutme":"關於LAI的事情",
        "side-slime":"史萊運轉",
        "side-ice":"破冰溝溝GO",
        "side-eraser":"腦內橡皮擦",
        "side-toki":"偷去",
        "side-seeyou":"大新街 LAST DANCE",
        "side-web":"網頁作品",
        "side-graphic":"平面作品",
        //
        "load": "自由に、自分らしく、思い切り振る舞う糸",
        "cover-title":"平面作品",
        "cover01":"字體設計 / 文宣設計 / 專案設計...各式各樣",
        "works01-1":"老港口",
        "works01-2":"品牌設計 / 2026",
        "works01-3":"品牌業主是坐落在古老港口街區大稻埕的咖啡廳。設計要點主要是以下三項。<br>窗花：以臺灣傳統建築特色的窗花為核心。窗花除了貼近庶民生活，更包含傳統社會的人文底蘊。<br>山海：「山」與「海」常作為兩種對比的概念，除了象徵餐飲事業將能提供的「山珍海味」，也具有遙遠與壯闊的意象，期許品牌能帶來遠近各異的風景。<br>集い：圖樣的形式與編排以「太極」為概念，山海也以同樣的方式向中央匯集。大稻埕即為物資集散中心，憑藉其深厚人文色彩匯聚各地遊客，同時，也期許品牌能匯聚各式各樣的「關係」於此。",
        "works01-4":"品牌卡片以透明材質製成。<br>分為兩種不同的設計，來訪的客人一次可獲得一張，而兩枚同時合併即可組合成品牌的ＬＯＧＯ。<br>A是大稻埕特有的紅色磚瓦建築，B則是發想自過去停泊在碼頭的貨船與航海藏寶圖。",
        "works02-1":"沒酒了，沒救了，梅酒ㄌ",
        "works02-2":"ＬＯＧＯ設計 / 2025",
        "works02-3":"「梅酒」、「沒酒」、「沒救」三者發音相近，便以此諧音作為本次活動的名稱。<br><br>這是一個所有參與者一起從零開始釀製梅酒的活動、因此我給他的關鍵字是「酒」與「熱鬧」。<br><br>依據客戶的喜好，製作成具有霓虹燈光效果的風格。在熱鬧街道的一隅經營私人小店的老闆，將自己樂於款待的心情寄於梅酒之中。",
        "works02-4":"原案：以燒灼的瓶身貼做為發想，以毛筆字呈現，並透過文字的編排來展現活力。",
        "works03-1":"要不要來我家看DISCO球",
        "works03-2":"專案設計 / 2024",
        "works03-3":"以購入迪斯可球為契機、「不如我們就來辦場迪斯可派對吧！」2000年前後出生的我們、並沒有可以一睹霓虹光彩與熱門舞曲的機會、甚至要依靠電視才能窺見舞廳的神秘面紗。<br><br>當時正好看完了日劇「極度不妥（不適切にもほどがある）」以劇中懷舊的視覺與熱鬧的氣氛為參考，將此定調為整個派對的主要視覺元素。<br><br>以參加者的人格特質做發想，製作了每人一張的獨特道具卡。同時也依據活動的整體視覺與元素製作了活動前導影片。",
        "works04-1":"ENGINE OIL 相關說明文宣",
        "works04-2":"文宣品設計 / 2025",
        "works04-3":"為知名潤滑油品牌・GOOD YEAR LUBRICANTS製作的引擎潤滑油相關知識文宣。<br><br>由於知識量密集，因此盡量讓資訊以圖像方式呈現，方便閱讀者理解與吸收。",
        "works05-1":"銷售BANNER",
        "works05-2":"文宣品設計 / 2024-2025",
        "works06-1":"教育實習成果發表會",
        "works06-2":"邀請函 / 2022",
        "works06-3":"為為期半年的教育實習畫下句點的實習成果發表會。發表會將聚集許多現場教師參與,因此以「宴會」為概念呈現出忙碌且熱鬧的氣氛。",
        "works07-1":"教學演示會",
        "works07-2":"海報、邀請函 / 2021",
        "works07-3":"教學演示會以國中二年級家政科的課程「服裝搭配」為主題。教案中取「一閃一閃」與「衣服」兩單詞的諧音,教材與演示文宣品都以「星空」為概念製作。<br><br>承襲此一概念,以明度與彩度較高的黄色與低明度的藍色結合,透過撞色的手法呈現出此課程開朗、活潑的意象。",
        "works08-1":"電繪作品",
        "works09-1":"手繪作品",
    },
    en: {
         // side
        "side-aboutme":"Things about LAI",
        "side-slime":"Tranditional Taiwanese snack renewal",
        "side-ice":"Onepage adult educational site",
        "side-eraser":"Typography & 3D-artwork",
        "side-toki":"The path I walked pass",
        "side-seeyou":"Project & visual design",
        "side-web":"When I meet programming",
        "side-graphic":"Some graphic works here",
        //
        "load": "Lines about split liberally and work as my-style",
        "cover-title":"GRAPHIC WORKS",
        "cover01":"Typography / Collateral Design / Project Design...and more",
        "works01-1":"Old Dock",
        "works01-2":"Brand Design / 2026",
        "works01-3":"A café brand in Dadaocheng, Taipei’s historic port district, built around three concepts:<br><br>Window Patterns — Inspired by traditional Taiwanese architecture and local culture.<br>Mountains & Sea — Representing contrast, abundance, and diverse scenery.<br>Gathering — A Taiji-inspired composition symbolizing Dadaocheng as a place where people and connections come together.",
        "works01-4":"Two transparent brand cards combine to reveal the complete logo. Card A features Dadaocheng’s red-brick architecture, while Card B is inspired by its historic port and cargo ships.",
        "works02-1":"There's no more alcohol,<br>no more hope, but plum wine",
        "works02-1-1":"There's no more alcohol, no more hope, but plum wine",
        "works02-2":"LOGO Design / 2025",
        "works02-3":"The similar pronunciations of “plum wine” (梅酒), “no alcohol” (沒酒), and “no hope” (沒救) inspired the event’s playful name.<br><br>Centered on “drinks” and “festivity,” the design uses a neon-inspired style to capture the lively and welcoming atmosphere of making plum wine together.",
        "works02-4":"Initial concept: Inspired by branded bottle labels, the design uses expressive brush lettering and dynamic typography to create a lively visual identity.",
        "works03-1":"Would you like to come over disco and cill",
        "works03-2":"Project Design / 2024",
        "works03-3":"It all started with a disco ball: “Why not throw a disco party?” Growing up in the 2000s, we never experienced the era of neon-lit dance halls and their vibrant nightlife firsthand.<br>Inspired by the Japanese drama “Extremely Inappropriate!,” I developed a retro disco-inspired visual direction for the party.<br><br>Each participant received a unique prop card inspired by their personality, along with a teaser video designed around the event’s visual identity.",
        "works04-1":"Engine Oil Flyer",
        "works04-2":"Collateral Design / 2025",
        "works04-3":"An educational promotional piece created for the well-known lubricant brand GOODYEAR LUBRICANTS.<br><br>To make the information easier to understand, dense technical content was transformed into clear, visual graphics.",
        "works05-1":"Sale Banner",
        "works05-2":"Collateral Design / 2024-2025",
        "works06-1":"Teaching Practicum Presentation",
        "works06-2":"Invitation Letter / 2022",
        "works06-3":"A presentation marking the completion of a six-month teaching practicum. Inspired by the lively atmosphere of a banquet, the visual concept reflects the energy and excitement of teachers gathering together.",
        "works07-1":"Teaching Demonstration",
        "works07-2":"Poster, Invitation Letter / 2021",
        "works07-3":"A teaching demonstration for an eighth-grade Home Economics lesson on clothing coordination. A Chinese wordplay combining “sparkle” and “clothing” inspired a starry-sky theme for both the teaching materials and promotional design.<br><br>Bright yellow and deep blue were paired in high contrast to create a cheerful and energetic visual identity.",
        "works08-1":"Digital Illustration",
        "works09-1":"hand-drawn Illustration",
    }
};