const translations = {
    zh: {
         // side
        "side-aboutme":"關於LAI的事情",
        "side-slime":"史萊運轉",
        "side-ice":"破冰溝溝GO",
        "side-eraser":"腦內橡皮擦",
        "side-toki":"偷去",
        "side-seeyou":"大新街 LAST DANCE",
        "side-web":"網頁作品",
        "side-graphic":"平面作品",
        //
        "load": "過去も自分の糧になり、人のための糸",
        "cover01":"資訊設計 / 一頁式網頁",
        "intro01":"建立人際關係重要的第一歩是 ...",
        "intro02":"針對 18-29 歳合計 200 左右的未婚男女進行問卷調査，顯示「溝通與衝突處理」是受試者們在親密關係中感到最棘手、難以面對的問題。<br>溝通雖然是生活中最普遍、基礎的關係建立媒介，但絕大多數的年輕人都對於溝通技巧缺乏瞭解,也不知道該如何改善。",
        "intro03":"問卷實行開始！",
        "intro03-1":"",
        "intro04":"”溝通與衝突處理”<span style="color:#000">的自評分數較低！</span>",
        "intro04-1":"",
        "intro05":"解決對策",
        "intro05-1":"",
        "type01":"",
        "element01":"",
        "element02":"",
    },
    en: {
         // side
        "side-aboutme":"Things about LAI",
        "side-slime":"Tranditional Taiwanese snack renewal",
        "side-ice":"Onepage adult educational site",
        "side-eraser":"Typography & 3D-artwork",
        "side-toki":"The path I walked pass",
        "side-seeyou":"Project & visual design",
        "side-web":"When I meet programming",
        "side-graphic":"Some graphic works here",
        //
        "load": "Lines about drawing strength from pass and experience",
        "cover01":"Information Design / Onepage site",
        "intro01":'The name of project "史萊運轉" is combined with "時來運轉" a madarin idiom and "slime" a monster by famous digital game series.<br><br>By regarding traditional snack as slimes from another world, just like you launch a challenge to them when eating them and finally receive the blessing after defeating enemies. "時來運轉"means luck would improve at the right time. Same as it, each traditional snack has their own blessing in.',
        "intro02":"",
        "intro03":"",
        "intro03-1":"",
        "intro04":"",
        "intro04-1":"",
        "intro05":"",
        "intro05-1":"",
        "type01":"",
        "element01":"",
        "element02":"",
    }
};