const translations = {
    zh: {
         // side
        "side-aboutme":"關於LAI的事情",
        "side-slime":"史萊運轉",
        "side-ice":"破冰溝溝GO",
        "side-eraser":"腦內橡皮擦",
        "side-toki":"偷去",
        "side-seeyou":"大新街 LAST DANCE",
        "side-web":"網頁作品",
        "side-graphic":"平面作品",
        //
        "load": "過去も自分の糧になり、人のための糸",
        "cover01":"資訊設計 / 一頁式網頁",
        "intro01":"建立人際關係重要的第一歩是 ...",
        "intro02":"針對 18-29 歳合計 200 左右的未婚男女進行問卷調査，顯示「溝通與衝突處理」是受試者們在親密關係中感到最棘手、難以面對的問題。<br>溝通雖然是生活中最普遍、基礎的關係建立媒介，但絕大多數的年輕人都對於溝通技巧缺乏瞭解,也不知道該如何改善。",
        "intro03":"問卷實行開始！",
        "intro03-1":"實施對象:18 歳到 29 歳的未婚男女<br>雖然知道人際應對與溝通技巧的重要性，也知道提升自己的溝通能力會是人際相處的重要課題，卻對改善方法毫無頭緒而無從下手。",
        "intro04":"”溝通與衝突處理”<span style="color:#000">的自評分數較低！</span>",
        "intro04-1":"相關領域之研究者所指出經營親密關係中重要的 8 項能力，針對這些能力依照自評該能力分數與自覺重要程度給予 0-5 分。依據數字大小表示該面向能力高低。",
        "intro05":"解決對策",
        "intro05-1":"以喚起視聽者的學習意識為目的，以少量的基礎知識作為本次素材。",
        "type01":"一頁式網站的模式讓全部五種類的溝通類型可以快速且大略地被瀏覽。<br>而對於想要了解更多詳細内容的讀者，可以選擇點撃各類型旁邊的手型圖示，便會透過彈出視窗提供關於該類型的詳細内容可供參考。",
        "element01":"點擊LOGO確認一頁式網站內容",
        "element02":"整體以「冰」為發想製作的文字為LOGO 主體。以冰塊沒有圓弧的特性，文字的設計也避免使用圓弧邊角，以硬轉折的筆畫製作。除此之外，也在部分筆畫中，以「冰柱」的概念加工。",
    },
    en: {
         // side
        "side-aboutme":"Things about LAI",
        "side-slime":"Tranditional Taiwanese snack renewal",
        "side-ice":"Onepage adult educational site",
        "side-eraser":"Typography & 3D-artwork",
        "side-toki":"The path I walked pass",
        "side-seeyou":"Project & visual design",
        "side-web":"When I meet programming",
        "side-graphic":"Some graphic works here",
        //
        "load": "Lines about drawing strength from pass and experience",
        "cover01":"Information Design / Onepage site",
        "intro01":'The first step to make greater relationship is...',
        "intro02":"A survey of roughly 200 unmarried adults aged 18-29 found that Communication & Conflict Resolution were considered the most challenged part in maintaining relationship.<br>Although communication is fundamental to build relationship, many young people have limited understanding of it and don' know how to improve them.",
        "intro03":"Questionary to focus on problem",
        "intro03-1":"Target Audiance: Unmarried adults aged 18-29<br>They understand importance of communication and want to build better relationship.However, they unsure how to do and where to start. ",
        "intro04":'<span style="color:#000">You scored relatively lower in </span>"Communication & Conflict Resolution"',
        "intro04-1":"Researchers in the field identified the 8 important skills for maintaining relationship. Each skill is rated on two dimenssion— self-assessed abillity and perceived importance— using scale from 0 to 5. A higher score indicates higher level in that area.",
        "intro05":"To break the status quo",
        "intro05-1":"The contents focuses on sparking readers' interest in learning more.",
        "type01":"Onepage site makes all of 5 communication types can be reviewed roughly and quickly.<br>For whom want to know more about it, the window contains detailed information would pop-up by clicking the hand-icon.",
        "element01":"Click LOGO to check the onepage site",
        "element02":"The logo around custom typography is inspired by ice. To reflect jagged nature of ice, the letters avoids rounded corner and uses sharp and geometric stroke instead. ",
    }
};