const translations = {
    zh: {
         // side
        "side-aboutme":"關於LAI的事情",
        "side-slime":"史萊運轉",
        "side-ice":"破冰溝溝GO",
        "side-eraser":"腦內橡皮擦",
        "side-toki":"偷去",
        "side-seeyou":"大新街 LAST DANCE",
        "side-web":"網頁作品",
        "side-graphic":"平面作品",
        //
        "load": "アージュドールに踊り、祝福を捧ぐ糸",
        "cover01":"專案設計 / 活動視覺",
        "intro01":"我有一個很愛邀請人來家裡玩的朋友。<br><br>三五好友聚在一起看場電影、享用晚餐、甚至是一起做料理，所有好玩有趣的事都在這個名為大新街的地方發生。然而，這個朋友準備搬家了，雖然並非再也見不到面，但是對於我們來說，這個充滿回憶的地方就像是生活中的桃源鄉一般。在這個無可取代的地方正式消失之前，我們決定再一次，放手地盡情狂歡。<br><br>這就是大新街LAST DANCE的起點。<br>以上古壁畫為發想，特別設計了畫面中登場的人物形式與整體顏色，並加上了宛如風化一般的陳舊質感。「在遙遠的未來，一個與現在完全不同的時代裡，那時的人們就可以透過這些畫作一窺這個地方曾經發生的事」視覺便是以此概念成形的。",
        "intro02":"活動行前通知（左）與<br>活動現場用入場簽到海報（上）。<br><br>基本上是依照主視覺的風格來統一製作。以做舊和無機的感覺還增添成品的神祕色彩。<br><br>入場簽到時可以選擇一個畫面中的icon並以畫筆將其延伸，同時留下對於這個地方想說的話。",
        "intro03":"活動用的前導短片也同樣依照前述的概念與風格製作，將在這個地方發生的所有快樂瞬間以照片形式復活。<br><br>在短片的最後融合了本次活動的重頭戲——卡片的設計（詳情稍後介紹）來製作，不斷變化的顏色以及在畫面上一閃而過的人物們與這個空間一起，成為這段神話不可或缺的一部分。",
        "card01":"在本次活動中，每一位蒞臨參加的來賓，都可以得到專屬於自己的三張卡片。<br><br>沿襲「因為有大家一起共同創造的回憶才會讓這個地方如此特別」的概念，每個人都是寄宿在這片荒土之上的神明。在這裡發生的所有事情、各自懷抱的不同煩惱都將作為刻劃在壁畫上的神話，在後世之間持續流傳。這也正可以呼應前面所述的「未來的人們將會透過留下來的這些資料持續考究當時在大新街的生活樣態」一概念。<br><br>卡片一共分為「肇始」「追逐」「旅程」三個不同的過程，並同時標示著故事的順序。而配合卡片的背面，則是對應著「熱絡」、「崩壞」、「終結」等三個階段的設計。卡片中所描述的故事與活動整體的設計與氛圍互相呼應扣合。<br><br>除此之外，每個人還會拿到屬於自己的卡片底座，並可以收納自己在活動中得到的卡片。將三枚卡片收入自己的底座後，可以直接作為展示架使用，將屬於自己的神話隨時保留在身邊。",
        "card02":"卡片底座‧正面",
        "card03":"放入卡片即可成為小型展示架！",
        "card04":'<span style="font-size: 25px;">肇始</span>',
        "card05":'<span style="font-size: 25px;">追逐</span>',
        "card06":'<span style="font-size: 25px;">旅程</span>',
        "list01":"一位三枚，<br>向這片大地賜予恩惠的神明們",
        "list02":"點擊卡片即可確認神明大人的故事！",
        "list-title01":"肇始",
        "list-title02":"追逐",
        "list-title03":"旅程",
        "display0101":"",
        "display0102":"",
        "display0103":"",
        "display0201":"",
        "display0202":"",
        "display0203":"",
        "display0301":"",
        "display0302":"",
        "display0303":"",
        "display0401":"",
        "display0402":"",
        "display0403":"",
        "display0501":"",
        "display0502":"",
        "display0503":"",
        "display0601":"",
        "display0602":"",
        "display0603":"",
        "display0701":"",
        "display0702":"",
        "display0703":"",
        "display0801":"",
        "display0802":"",
        "display0803":"",
        "display0901":"",
        "display0902":"",
        "display0903":"",
        "display1001":"",
        "display1002":"",
        "display1003":"",
        "display1101":"",
        "display1102":"",
        "display1103":"",
        "display1201":"",
        "display1202":"",
        "display1203":"",
        "display1301":"",
        "display1302":"",
        "display1303":"",
        "display1401":"",
        "display1402":"",
        "display1403":"",
        "display1501":"",
        "display1502":"",
        "display1503":"",
        "display1601":"",
        "display1602":"",
        "display1603":"",
        "display1701":"",
        "display1702":"",
        "display1703":"",
        "display1801":"",
        "display1802":"",
        "display1803":"",
        "display1901":"",
        "display1902":"",
        "display1903":"",
        "display2001":"",
        "display2002":"",
        "display2003":"",
        "display2101":"",
        "display2102":"",
        "display2103":"",
    },
    en: {
         // side
        "side-aboutme":"Things about LAI",
        "side-slime":"Tranditional Taiwanese snack renewal",
        "side-ice":"Onepage adult educational site",
        "side-eraser":"Typography & 3D-artwork",
        "side-toki":"The path I walked pass",
        "side-seeyou":"Project & visual design",
        "side-web":"When I meet programming",
        "side-graphic":"Some graphic works here",
        //
        "load": "Lines about dancing and<br>wishing for the golden age",
        "cover01":"Project Design / Event Visual",
        "intro01":"",
        "intro02":"",
        "intro03":"",
        "card01":"",
        "card02":"",
        "card03":"",
        "card04":"",
        "card05":"",
        "card06":"",
        "list01":"",
        "list02":"",
    }
};