const translations = {
    zh: {
         // side
        "side-aboutme":"關於LAI的事情",
        "side-slime":"史萊運轉",
        "side-ice":"破冰溝溝GO",
        "side-eraser":"腦內橡皮擦",
        "side-toki":"偷去",
        "side-seeyou":"大新街 LAST DANCE",
        "side-web":"網頁作品",
        "side-graphic":"平面作品",
        //
        "load": "アージュドールに踊り、祝福を捧ぐ糸",
        "cover01":"專案設計 / 活動視覺",
        "intro01":"我有一個很愛邀請人來家裡玩的朋友。<br><br>三五好友聚在一起看場電影、享用晚餐、甚至是一起做料理，所有好玩有趣的事都在這個名為大新街的地方發生。然而，這個朋友準備搬家了，雖然並非再也見不到面，但是對於我們來說，這個充滿回憶的地方就像是生活中的桃源鄉一般。在這個無可取代的地方正式消失之前，我們決定再一次，放手地盡情狂歡。<br><br>這就是大新街LAST DANCE的起點。<br>以上古壁畫為發想，特別設計了畫面中登場的人物形式與整體顏色，並加上了宛如風化一般的陳舊質感。「在遙遠的未來，一個與現在完全不同的時代裡，那時的人們就可以透過這些畫作一窺這個地方曾經發生的事」視覺便是以此概念成形的。",
        "intro02":"活動行前通知（左）與<br>活動現場用入場簽到海報（上）。<br><br>基本上是依照主視覺的風格來統一製作。以做舊和無機的感覺還增添成品的神祕色彩。<br><br>入場簽到時可以選擇一個畫面中的icon並以畫筆將其延伸，同時留下對於這個地方想說的話。",
        "intro03":"活動用的前導短片也同樣依照前述的概念與風格製作，將在這個地方發生的所有快樂瞬間以照片形式復活。<br><br>在短片的最後融合了本次活動的重頭戲——卡片的設計（詳情稍後介紹）來製作，不斷變化的顏色以及在畫面上一閃而過的人物們與這個空間一起，成為這段神話不可或缺的一部分。",
        "card01":"在本次活動中，每一位蒞臨參加的來賓，都可以得到專屬於自己的三張卡片。<br><br>沿襲「因為有大家一起共同創造的回憶才會讓這個地方如此特別」的概念，每個人都是寄宿在這片荒土之上的神明。在這裡發生的所有事情、各自懷抱的不同煩惱都將作為刻劃在壁畫上的神話，在後世之間持續流傳。這也正可以呼應前面所述的「未來的人們將會透過留下來的這些資料持續考究當時在大新街的生活樣態」一概念。<br><br>卡片一共分為「肇始」「追逐」「旅程」三個不同的過程，並同時標示著故事的順序。而配合卡片的背面，則是對應著「熱絡」、「崩壞」、「終結」等三個階段的設計。卡片中所描述的故事與活動整體的設計與氛圍互相呼應扣合。<br><br>除此之外，每個人還會拿到屬於自己的卡片底座，並可以收納自己在活動中得到的卡片。將三枚卡片收入自己的底座後，可以直接作為展示架使用，將屬於自己的神話隨時保留在身邊。",
        "card02":"卡片底座‧正面",
        "card03":"放入卡片即可成為小型展示架！",
        "card04":'<span style="font-size: 25px;">肇始</span>',
        "card05":'<span style="font-size: 25px;">追逐</span>',
        "card06":'<span style="font-size: 25px;">旅程</span>',
        "list01":"一位三枚，<br>向這片大地賜予恩惠的神明們",
        "list02":"點擊卡片即可確認神明大人的故事！",
        "list-title01":"肇始",
        "list-title02":"追逐",
        "list-title03":"旅程",
        "display0101":"空氣劍道大師的第一門徒，跟隨在側，你默默洞悉了門派劍法，如水無形、如氣輕盈，劍如其人，在千變萬化的想法中綻放。",
        "display0102":"你創立門派、培育後進，你端詳徒弟們的青澀，看著日漸茁壯的翠苗，你感受到身為教育者的以身作則，想要樹立榜樣與愛。",
        "display0103":"貳伍春末、空氣劍客的對決，高手過招，你伸手索敵、感受空間的氣息，不料對方感受到你的聲息，對你使出致命一擊。",
        "display0201":"被幸運之神眷顧的孩子，天空因你而放晴、骰子因你而聽令，你是好運狙擊手，狙擊每個可能性。",
        "display0202":"敲擊太鼓的鼓棒、拍打木箱鼓的雙手，你是浪漫的實踐家，打響節拍，只為此刻的熠光而奏",
        "display0203":"眾人因你的溫暖而產生緣分的交織，你最大的幸運，是擁有許多真摯的夥伴，而你的存在，也是夥伴們的幸運。",
        "display0301":"千萬把鑰匙落下的雨，鑰匙沉入泥濘，左腳、右腳、左腳、右腳，你奮力向前，尋找方向。",
        "display0302":"千變的林木交織，撥開樹葉，你發現了一扇佇立於泉水之上的門扉，泉水從中湧出、清澈而靜謐。",
        "display0303":"你嘗試推開，未果。你撫著胸口，深呼吸，仰望未被樹林遮蔭的天空，暖意竄流全身匯集到掌心，成為你手中握著的鑰匙。",
        "display0401":"雙手撥弄琴絃，歌聲穿透在場的每個人，眾人齊聲歡唱，你是氣氛的指揮家，現場的氛圍因你而改變。",
        "display0402":"出發演奏前，鏡面上映照你流下的淚水，擔憂、恐懼、焦慮，你戴上面具、擦乾淚水，笑稱自己是鐵娘子。",
        "display0403":"你練習展現脆弱，脆弱化成柔軟與細膩，而過往的武裝則變成堅毅與勇氣，拓展你未來的邊際。",
        "display0501":"落雨不斷的樹林，你從中誕生，無人知曉何時雨停，若有機會，成為神仙吧！「因為神仙不會哭也不會痛。」",
        "display0502":"你吃下一顆顆仙丹，他們說吃了可以召喚暖陽，而你只是越睡越沉，深潛入黑暗無光的深淵。",
        "display0503":"面對黑暗，心頭發出微光，那光像金絲，引領你迴游，你回到樹林，胸口的金絲綻放，成為了照亮樹林的暖陽。",
        "display0601":"吹奏著口琴，五線譜交織過往成為珍貴的緣分，音符與旋律，證明了曾經的熱愛以及付出。",
        "display0602":"青春的佈告欄，上面貼滿青春的言語，你用心的回覆，讓每個青春躍動的心得到承接。",
        "display0603":"實踐愛與榜樣的路上，日常的累積成為前行的台階，付出愛的同時也漸漸得到愛自己的能力。",
        "display0701":"洞窟水滴聲此起彼落、幽微的海潮聲迴響，你拿出探照燈，千萬的貝類滿佈洞穴，你伸手取下最大珍珠，觸怒了貝殼之主，驅趕你前往下一場冒險。",
        "display0702":"熱帶的島嶼、海邊的古廟、翠綠的農田、駕馭未知的生物、敲響古老的樂器，你的熱情相襯標誌性的紅髮，所到之處皆是歡笑。",
        "display0703":"派對後的夜晚，捲菸點燃，「工作與產出是創意的實踐。」廣博的閱歷成為你的品味，犀利的目光指引你，在未來交織人際、譜寫你對社會的改變。",
        "display0801":"穿刺手臂的花、萌芽的勇氣，過往血與淚的澆灌，化作堅定的暖陽，滋養著內心向外探險的種子，盛開堅毅的勇氣之花。",
        "display0802":"古城、雨林、熱帶島嶼，界線與規則束縛不了你，你帶回古書、奇特的藥草，在所到之處抓緊每個當下、轟轟烈烈的活。",
        "display0803":"晨光灑在桌上，咖啡香瀰漫，杯中的水霧、燃燒的香菸，「以後我們開店開在蘭嶼」嬉鬧帶著認真，時間會確認承諾的兌現。",
        "display0901":"圈養著裸身的小動物們，他們的野性、自然，是你心中澄清的湖面，小動物跟著你，在所到之處留下可愛的腳印。",
        "display0902":"過往在操場嬉鬧的青年、充滿想像的種子，才能的萌芽、感受的積累，你帶著一枝蘭花出現，與摯友把酒言歡，是關係與緣分的綻放。",
        "display0903":"派對後的夜晚，捲菸點燃，「這個過程很美。」木頭的切割、組合讓你著迷，與他人分享著你所見的美，對色彩與繪畫的掌握，成為指引你未來的舵。",
        "display1001":"無法捉摸的水仙精靈，你拉著人們與你一起嬉戲，就算一起入浴也不害臊。",
        "display1002":"過往的困頓、心靈的紛擾，你嘗試找尋那湖水的源頭，未果，你仍持續探詢，心頭未知的解答。",
        "display1003":"看著湖面自己的面孔，過往模糊的感受愈漸清晰，如常的生活產生不一樣的漣漪。",
        "display1101":"你悠然在海中遨遊，那溫暖而神秘的黃色結晶，構成了你自在而歡快的心。",
        "display1102":"你時常在海岸邊歌唱，跟經過的旅人們成為朋友，你的善良讓每段際遇都充滿真誠與快樂。",
        "display1103":"結識各路的旅人，你書寫下每段回憶、收集成冊，放在你常出沒的海岸上，成為旅人再度回訪的溫暖回憶。",
        "display1201":"你身處一個神奇的電話亭中，外面晴空萬里，只有電話亭內下著雨，拿起話筒，卻不知道該跟誰說起。",
        "display1202":"你走向外面，踏出的每一步都是編織未知的旅途。你學會異國的咒語，馴服巨人、踏上極地、與異國住民相識。",
        "display1203":"在無人的頂樓搖擺，俯瞰老舊的街道。「因為我很努力了啊！」，回首過往的實踐，如今萌生短暫在異國生活的想像，你張開雙臂，收集群風。",
        "display1301":"快活快活，心中有佛，得號「快佛」。在笑談中桿麵，每食每餐懷著深刻的感恩。",
        "display1302":"拄著向日葵法杖，行走於陰暗幽谷、踏遍生命的無常，每日的甦醒、血液的流淌，因你深知黑暗，得以體會暖陽。",
        "display1303":"你伸手一揮，太陽花瓣鋪成橋樑，交織與他人深刻交流的緣分，溫暖而真誠。",
        "display1401":"你是好奇小精靈們的嚮導，帶著他們看遍百工百業，小精靈專注看著陶藝匠人拉胚，而你看著他們的成長。",
        "display1402":"對生活本質的掌握，使你的靈魂向下扎根，希冀的生活、更熟悉的自我，成為滋長的養分。",
        "display1403":"制度的籬笆成為養分，萌生改變的想法，過往的枷鎖，將成為創造未來的能量。",
        "display1501":"洞悉人性，你是話語的魔術師，就連多疑的貝殼之主都被你馴服，真誠就是你的武器，得以建立許多情誼。",
        "display1502":"曾被遺留在無人的深淵，黑暗將你的情緒與感受壓縮，那是你從未與他人訴說的夢。",
        "display1503":"你重回夢中的深淵，撿起被遺留的碎片，碎片匯聚成發光的晶體，化作未來前行的勇氣。",
        "display1601":"華美的鳥，展開千百隻眼的羽衣。夢中你墜入黑暗的漩渦，得到看透他人內心的魔法。",
        "display1602":"千百隻眼映照著他人，也看穿自我，你用層層羽翼包圍，那從未展現於他人的心。",
        "display1603":"羽毛的銳利逐漸圓滑，揮舞翅膀，向未知的天空找尋方向，那善於看破本質的目光，保護你自由在空中翱翔。",
        "display1701":"你爬上高塔，菸花佔據了眼前，你收下香菸，那是最後一支，你吸入一口，將過往的經歷轉化為縷縷青煙，吐出的是生活中的感受與淬鍊。",
        "display1702":"「無常與變動，能抓住的只有現在」文字組成的船、音符織起的帆，你抓著舵、抓著當下，航向未知的遠方。",
        "display1703":"躺在草地，望向眼前的羔羊們，熟練而如常引導他們，小羊們時而鬧得你又氣又好笑。",
        "display1801":"背著烏克麗麗，譜出細膩溫柔的想法，你是吟遊詩人，跟隨著高掛黑夜的天狼星，收集每個快樂的瞬間。",
        "display1802":"打開筆捲袋，你描繪著腳前的銀河，踏於繁星，捕捉所到之處的閃亮，成為照亮他人的星光。",
        "display1803":"一片又一片，組合起開心回憶的拼圖，你看著一幅幅被你完整的畫面，成為描繪未來的七彩顏料。",
        "display1901":"花瓣展開、沐浴朝陽，鮮少有人到達你盛開的山峰，你眺望著無人看過的美景，渴望去到更高的地方。",
        "display1902":"某天巫師遇見了你，以原本的型態為代價，你得到了軀幹與可以遠行的雙腳。",
        "display1903":"你在追逐遠方的過程，也在找回原本的自己，而只有找到心中那片寧靜，旅行才有可能消停。",
        "display2001":"「拿起你的酒杯，不醉不歸！」五光十色的夜晚，歡快的氣氛因你而起，歡聲迴盪、觥籌交錯。",
        "display2002":"未來的選擇像是迷宮，你困於其中躊躇，不斷的嘗試與突破，你漸漸找到前行的節奏。",
        "display2003":"開放的心成為你的羅盤，謹慎的性格成為你的保護傘，即便面臨汪洋與漩渦，仍使你安穩前行。",
        "display2101":"徐風輕摟，挾帶著菸草的餘韻，伴著熙來攘往的旅人，你感應到魔境中的能量正在翻騰。",
        "display2102":"青梅、砂糖、酒精——你無數次燃起煉金的大釜，只為抓住一絲魔境的餘輝。",
        "display2103":"你闔上大門，以為從此回歸平凡。然而所謂魔境只是虛泛，魔力始終源自你的玩心。",
    },
    en: {
         // side
        "side-aboutme":"Things about LAI",
        "side-slime":"Tranditional Taiwanese snack renewal",
        "side-ice":"Onepage adult educational site",
        "side-eraser":"Typography & 3D-artwork",
        "side-toki":"The path I walked pass",
        "side-seeyou":"Project & visual design",
        "side-web":"When I meet programming",
        "side-graphic":"Some graphic works here",
        //
        "load": "Lines about dancing and<br>wishing for the golden age",
        "cover01":"Project Design / Event Visual",
        "intro01":"I have a friend who loves inviting people over.<br><br>Movies, dinners, cooking together—so many memories were made in this place called Daxin Street. Before my friend moved away and this irreplaceable place disappeared from our everyday lives, we decided to celebrate there one last time.<br><br>This became the beginning of Daxin Street LAST DANCE.<br>Inspired by ancient murals, the characters, colors, and weathered textures were designed as traces left behind for the distant future—as if people from another era could discover what once happened here.",
        "intro02":"Pre-event notice (left) and check-in poster used at the venue (above).<br><br>Both follow the main visual style, using aged and raw textures to create a mysterious atmosphere.<br><br>At check-in, guests could choose an icon, extend it with a brush, and leave a message for this place.",
        "intro03":"The teaser video follows the same visual concept, bringing joyful memories from this place back to life through photographs.<br><br>It ends by introducing the event’s key feature—the cards. Shifting colors and passing characters become part of the mythology of this space.",
        "card01":"Each guest receives three personalized cards.<br><br>Built around the idea that this place became special through memories created together, every guest is portrayed as a deity who once lived upon this land. Their experiences and struggles become myths engraved into its murals and passed on to the future.<br><br>The cards follow three stages—“Beginning,” “Pursuit,” and “Journey”—while their reverse sides correspond to “Flourishing,” “Collapse,” and “Ending.” Together, they form each person’s story within the world of the event.<br><br>Each guest also receives a personal card holder. Once all three cards are inserted, it becomes a small display stand for keeping their own mythology close.",
        "card02":"Card Holder · Front",
        "card03":"Insert the cards to create a mini display stand!",
        "card04":'<span style="font-size: 25px;">肇始</span> / Beginning',
        "card05":'<span style="font-size: 25px;">追逐</span> / Pursuit',
        "card06":'<span style="font-size: 25px;">旅程</span> / Journey',
        "list01":"Three cards for each<br>deity who blessed this land",
        "list02":"Click a card to discover each deity’s story!",
        "list-title01":"Beginning",
        "list-title02":"Pursuit",
        "list-title03":"Journey",
        "display0101":"The first disciple of the Air Sword Master, you quietly mastered a style as fluid as water and light as air. Like its wielder, your sword blooms through ever-changing ideas.",
        "display0102":"You founded a school and raised new disciples. Watching them grow, you learned the responsibility of an educator—to lead by example, with both guidance and care.",
        "display0103":"Late spring of ’25, the air swordsmen faced off. You reached out to sense your rival, but they caught your presence first and struck a fatal blow.",
        "display0201":"Favored by the god of luck, the skies clear for you and dice obey your hand. You are a sniper of fortune, taking aim at every possibility.",
        "display0202":"Drumsticks strike the taiko, hands beat the cajón. You are a romantic in action, playing each rhythm for the brilliance of this very moment.",
        "display0203":"Your warmth brings people together. Your greatest fortune is having sincere companions—and to them, your presence is part of their good fortune too.",
        "display0301":"Millions of keys rain from above and sink into the mud. Left foot, right foot—you press onward, searching for a direction.",
        "display0302":"Beyond tangled trees, you find a door standing above a spring. Clear and silent water flows from within.",
        "display0303":"You try to open it, but fail. Taking a deep breath, warmth gathers in your palm and becomes the key you have been searching for.",
        "display0401":"Your fingers move across the strings and your voice carries through the room. Everyone joins in—you are the conductor of the atmosphere.",
        "display0402":"Before the performance, tears appear in the mirror—fear, worry, anxiety. You put on your mask, wipe them away, and jokingly call yourself an iron lady.",
        "display0403":"You learn to show vulnerability. It becomes softness and sensitivity, while your old armor transforms into strength and courage for what lies ahead.",
        "display0501":"You are born in a forest of endless rain. No one knows when it will stop. Perhaps you could become an immortal—“Immortals never cry or hurt.”",
        "display0502":"You swallow one elixir after another, told they can summon the sun. Instead, you sink deeper into sleep and descend into a lightless abyss.",
        "display0503":"Within the darkness, a golden thread of light guides you back. Returning to the forest, it blooms from your chest and becomes the warm sun above.",
        "display0601":"You play the harmonica as musical lines weave past memories into precious bonds. Every note proves the passion and effort once given.",
        "display0602":"A bulletin board of youth is covered in restless thoughts. Your thoughtful replies give each young heart a place to land.",
        "display0603":"On the path of love and example, everyday effort becomes each step forward. In giving love, you gradually learn how to give it to yourself.",
        "display0701":"Drops echo through a sea cave. Under your searchlight lie countless shells. You take the largest pearl, angering their lord and sending yourself toward another adventure.",
        "display0702":"Tropical islands, ancient seaside temples, green fields, strange creatures and old instruments—your red hair and passion carry laughter wherever you go.",
        "display0703":"After the party, a cigarette burns. “Work and creation are how ideas become real.” Your broad experiences shape your taste, while your sharp eye guides what you create next.",
        "display0801":"A flower pierces your arm and courage begins to sprout. Past blood and tears become sunlight, nourishing the seed of adventure until it blooms with strength.",
        "display0802":"Ancient cities, rainforests, tropical islands—rules and borders cannot hold you. You return with old books and strange herbs, living fiercely wherever you go.",
        "display0803":"Morning light falls across the table, mixed with coffee and smoke. “One day, let’s open a shop in Lanyu.” Half joking, half sincere—time will test the promise.",
        "display0901":"You care for tiny creatures in their natural form. Their wildness reflects the clear lake within you, leaving small, playful footprints wherever you go.",
        "display0902":"A youth once playing on the field grows through imagination and experience. Carrying an orchid, you reunite with old friends over drinks as bonds quietly bloom.",
        "display0903":"After the party, a cigarette glows. “The process itself is beautiful.” Cutting and joining wood fascinates you, while your eye for color and drawing becomes a compass for the future.",
        "display1001":"An elusive water spirit, you pull everyone into your games—even sharing a bath without the slightest embarrassment.",
        "display1002":"Through past confusion and inner turmoil, you search for the source of the lake. You cannot find it, yet continue seeking the unanswered question within.",
        "display1003":"Looking at your reflection on the lake, feelings once blurred begin to sharpen. Even ordinary life starts forming unfamiliar ripples.",
        "display1101":"You drift freely through the sea, a warm and mysterious yellow crystal forming the carefree joy within you.",
        "display1102":"You often sing by the shore and befriend passing travelers. Your kindness turns every encounter into something sincere and joyful.",
        "display1103":"You record each encounter and gather the memories into a book, leaving it by your familiar shore as a warm reason for travelers to return.",
        "display1201":"You stand inside a strange phone booth. The sky outside is clear, yet rain falls only within. You lift the receiver, unsure who to call.",
        "display1202":"You step outside, each footstep weaving an unknown journey. You learn foreign spells, tame giants, cross polar lands, and meet people from distant worlds.",
        "display1203":"You sway alone on a rooftop overlooking old streets. “I really did try my best.” Looking back, you begin imagining life abroad and open your arms to gather the wind.",
        "display1301":"Joyful at heart and mindful of gratitude, you earn the name “Happy Buddha,” kneading dough through laughter and appreciating every meal.",
        "display1302":"With a sunflower staff, you walk through dark valleys and witness life’s impermanence. Because you know darkness, each waking day feels touched by sunlight.",
        "display1303":"With a wave of your hand, sunflower petals form a bridge, connecting you to deep and sincere bonds with others.",
        "display1401":"You guide curious little spirits through countless professions. As they watch a potter shape clay, you quietly watch them grow.",
        "display1402":"Understanding what matters in life lets your spirit take root. The life you hope for and the self you know better become nourishment for growth.",
        "display1403":"Even the fences of old systems become nourishment. Past restraints transform into the energy needed to imagine and create change.",
        "display1501":"You understand people deeply and wield words like magic. Even the suspicious Lord of Shells trusts you—sincerity is the weapon behind your many friendships.",
        "display1502":"Once abandoned in a lightless abyss, your emotions were compressed into a dream you never shared with anyone.",
        "display1503":"You return to that abyss and gather the forgotten fragments. They merge into a glowing crystal, becoming courage for the path ahead.",
        "display1601":"A magnificent bird spreads feathers covered in countless eyes. Falling into darkness in a dream, you gain the power to see into other hearts.",
        "display1602":"Those countless eyes reflect others—and yourself. Layer after layer of wings surround the heart you have never shown.",
        "display1603":"Your sharp feathers slowly soften. You spread your wings toward an unknown sky, guided and protected by your ability to see beneath the surface.",
        "display1701":"You climb a tower surrounded by tobacco flowers and receive one final cigarette. Inhaling the past, you exhale everything life has taught you.",
        "display1702":"“In a world of change, only the present can be held.” Words form your boat, notes become its sail, and you steer toward the unknown.",
        "display1703":"Lying in the grass, you watch over a flock of lambs with practiced ease, amused and frustrated by their endless mischief.",
        "display1801":"With a ukulele on your back, you turn gentle thoughts into songs. A wandering bard beneath Sirius, you collect every joyful moment along the way.",
        "display1802":"You open your pencil roll and sketch the galaxy beneath your feet, gathering every sparkle you encounter until you become a light for others.",
        "display1803":"Piece by piece, joyful memories become a completed puzzle. Each finished scene turns into new colors for painting the future.",
        "display1901":"Petals unfold beneath the morning sun. Few reach the peak where you bloom, yet you gaze toward unseen views and long to climb still higher.",
        "display1902":"One day, a wizard finds you. In exchange for your original form, you receive a body and two legs made for distant journeys.",
        "display1903":"While chasing distant places, you also search for the self you left behind. Only by finding inner stillness can the journey finally rest.",
        "display2001":"“Raise your glass—we drink until dawn!” A brilliant night comes alive around you, filled with laughter, cheers, and clinking glasses.",
        "display2002":"The future becomes a maze of choices. Through hesitation, trial, and breakthrough, you slowly find your rhythm forward.",
        "display2003":"An open heart becomes your compass, caution your shelter. Even through open seas and whirlpools, they keep you moving steadily ahead.",
        "display2101":"A soft breeze carries traces of tobacco as travelers pass by. Around you, the strange realm begins to stir with energy.",
        "display2102":"Green plums, sugar, alcohol—you ignite the alchemist’s cauldron again and again, trying to capture a fragment of its magic.",
        "display2103":"You close the door, thinking ordinary life has returned. But the magical realm was only an illusion—the magic had always come from your playful heart."
    }
};